name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Elm tools and cache $ELM_HOME
        uses: mpizenberg/elm-tooling-action@v1.1
        with:
          cache-key: elm-tooling

      - name: elm-format
        uses: sparksp/elm-format-action@v1.0.2

      - name: elm-review
        uses: sparksp/elm-review-action@v1.0.6
        with:
          elm_review: npx elm-review
          elm_compiler: ./node_modules/.bin/elm
          elm_format: ./node_modules/.bin/elm-format

      - name: elm-test-rs
        run: ./node_modules/.bin/elm-test-rs
